/* Shared icon resolution — used across builds, crafting, analyser, etc.
 *
 * Ascendancy backgrounds: generated by backend/scripts/slice_ascendancy_backgrounds.py
 * which extracts the PoB sprite atlas into /public/images/ascendancies/{slug}.webp.
 *
 * Skill gem icons: not yet sourced (PoB doesn't ship them). When they land,
 * drop them into /public/images/skills/{slug}.webp. Until then `<img>` 404s
 * and the component falls back to a Cinzel-letter glyph.
 *
 * Item icons: extracted from PoE2 bundles by backend/scripts/icon_extract/extract_all.mjs.
 * PNGs live at /public/icons/items/{ItemVisualIdentity-id}.png (gitignored, regen on patch);
 * the name→id lookup itemIcons.json (committed alongside this file) covers
 * every PoE2 base item including currencies, essences, omens — so
 * itemIconPath resolves crafting currencies as well as gear bases.
 */

import itemIcons from "./itemIcons.json";

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/['']/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function skillIconPath(skill: string): string {
  return `/images/skills/${slugify(skill)}.webp`;
}

export function ascendancyIconPath(ascendancy: string): string {
  return `/images/ascendancies/${slugify(ascendancy)}.webp`;
}

export function skillInitial(skill: string): string {
  return skill.replace(/\s+/g, "").slice(0, 1).toUpperCase();
}

const uniques: Record<string, string> = itemIcons.uniques;
const bases:   Record<string, string> = itemIcons.bases;

/** Resolve an item to its icon URL. Tries unique name first, falls back to base name. */
export function itemIconPath(name: string | null | undefined, base?: string | null): string | null {
  const id = (name && uniques[name]) || (base && bases[base]) || (name && bases[name]);
  return id ? `/icons/items/${id}.png` : null;
}
